version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_Password
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    networks:
      - default
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=Your_Host 
      - DB_PORT=Your_Port
      - DB_DATABASE=AeC
      - DB_USERNAME=sa
      - DB_PASSWORD=Your_Password
    ports:
      - 8090:80
    networks:
      - default
