version: '3.8'

services:
  # Configuração do SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: 123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  # Configuração da aplicação .NET
  myapp:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: myapp
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=AeC;User Id=sa;Password=123;"
    build:
      context: ./App  # Substitua pelo diretório do seu aplicativo .NET
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-server
    networks:
      - mynetwork

networks:
  mynetwork:
